export const REQUEST_FETCH = 'FETCH_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SYNC = 'SYNC';

export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAILED = 'ADD_PATIENT_FAILED';
export const GET_PATIENT_SUCCESS = 'GET_PATIENT_SUCCESS';
export const GET_PATIENT_FAILED = 'GET_PATIENT_FAILED';
export const EDIT_PATIENT_SUCCESS = 'EDIT_PATIENT_SUCCESS';
export const EDIT_PATIENT_FAILED = 'EDIT_PATIENT_FAILED';
export const REMOVE_PATIENTS = 'REMOVE_PATIENTS';
export const SET_CURRENT_PATINET = 'SET_CURRENT_PATINET';

export const ADD_TREATMENT_SUCCESS = 'ADD_TREATMENT_SUCCESS';
export const ADD_TREATMENT_FAILED = 'ADD_TREATMENT_FAILED';
export const EDIT_TREATMENT_SUCCESS = 'EDIT_TREATMENT_SUCCESS';
export const EDIT_TREATMENT_FAILED = 'EDIT_TREATMENT_FAILED';
export const REMOVE_TREATMENT = 'REMOVE_TREATMENT';

export const GET_TREATMENTS_SUCCESS = 'GET_TREATMENTS_SUCCESS';
export const GET_TREATMENTS_FAILED = 'GET_TREATMENTS_FAILED';
